image: docker:latest

services:
  - docker:dind

stages:
  - phpcs
  - test
  - build


variables:
  PHP_BASE_VERSION: "01016ecf" # https://gitlab.com/img-docker/php

  IMAGE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  PHP_IMAGE: "registry.gitlab.com/img-docker/php:8.3.15-fpm-$PHP_BASE_VERSION"

phpcs:
  stage: phpcs
  script:
    - apk add --no-cache make
    - make phpcs

test:
  stage: test
  script:
    - docker run -v $PWD:/app composer:2.8.4 composer install --ignore-platform-reqs

    - echo $KEY_PHP_BASE_PASSWORD | docker login -u $KEY_PHP_BASE_USER --password-stdin registry.gitlab.com
    - docker pull $PHP_IMAGE
    - docker run -v $PWD:/var/www $PHP_IMAGE php -d memory_limit=-1 /var/www/vendor/bin/phpunit

build:
  stage: build
  script:
    - echo $KEY_PHP_BASE_PASSWORD | docker login -u $KEY_PHP_BASE_USER --password-stdin registry.gitlab.com
    - docker pull $PHP_IMAGE

    - SHORT_TAG=${CI_COMMIT_SHA:0:8}
    - docker build -t $IMAGE:latest -t $IMAGE:$SHORT_TAG ./.docker/

    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker push $IMAGE:latest
    - docker push $IMAGE:$SHORT_TAG
  only:
    - main
