services:
  php-shop:
    image: ${IMAGE}:${VERSION}
    build:
      context: ./.docker/
    container_name: php-shop
    restart: no
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - web-network-shop

networks:
  web-network-shop:
    name: web-network-shop
    driver: bridge
