services:
  nginx-shop:
    container_name: nginx-shop
    image: nginx:1.24
    restart: no
    volumes:
      - .:/var/www/
      - ./.docker/config/nginx/:/etc/nginx/conf.d/
      - ./.docker/logs/nginx:/var/log/nginx/
    ports:
      - "80:80"
    networks:
      - web-network-shop

  php-shop:
    image: ${IMAGE}:${VERSION}
    build:
      context: ./.docker/
    container_name: php-shop
    restart: no
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - web-network-shop

  redis-shop:
    container_name: redis-shop
    image: redis:7.4.0-alpine
    restart: no
    networks:
      - web-network-shop

  db-shop:
    container_name: db-shop
    image: mysql:8.4.3
    restart: no
    ports:
      - "3317:3306"
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop
    security_opt:
      - seccomp:unconfined
    volumes:
      - database-shop-v1:/var/lib/mysql
    networks:
      - web-network-shop

volumes:
    database-shop-v1:
        name: database-shop-v1

networks:
  web-network-shop:
    name: web-network-shop
    driver: bridge
