services:
  php-shop:
    image: ${IMAGE}:${VERSION}
    build:
      context: ./.docker/
    container_name: php-shop
    restart: no
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - web-network-shop
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  web-network-shop:
    name: web-network-shop
    driver: bridge
